# Minecraft & Fabric
minecraft_version=26.2
loader_version=0.19.3
fapi_version=0.153.0+26.2

# Mod
mod_version=1.5.2
maven_group=com.srendi
archives_base_name=SerendiModGuarder

# Toolchain — help Gradle find JDK 25
org.gradle.java.installations.paths=C\:\\Users\\27427\\AppData\\Local\\Programs\\Microsoft\\jdk-25.0.2.10-hotspot
